config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get "home/team"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :common, :only => [:index, :team]

  def common
    @hero_descriptor = Faker::Superhero.descriptor
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @hero_prefix = Faker::Superhero.prefix
    @hero_suffix = Faker::Superhero.suffix
    @hero_profession = Faker::Company.profession.titleize
    @hero_company_bs = Faker::Company.bs.titleize
    # Build Full Name
    @hero_fullname = @hero_prefix + ' ' + @hero_name + ' ' + @hero_suffix
    # Build Avatar
    @set = "set" + randomizer(2).to_s
    @bg = "bg" + randomizer(2).to_s
    @hero_avatar = Faker::Avatar.image(@hero_fullname, "300x300", "png", @set, @bg)
  end

  def index
  end

  def team
  end

  private
  def randomizer(key)
    rand(1..key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'SuperHero Name Generator', root_path, class:'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav"></ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home Page', root_path %></li>
                <li><%= link_to 'Create a Team', home_team_path %></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to 'Click Here To Generate A New Superhero', root_path %></h3>
  </div>
  <div class="panel-body">
    <img src="<%= @hero_avatar %>" alt="Hero Avatar" /><br/><br/>

    Your Superhero Name:<br/>
    <%= @hero_fullname %><br/>
    Your Superhero Power:<br/>
    <%= @hero_power %><br/><br/>

    Your Undercover Day Job is:<br/>
    <%= @hero_profession %><br/><br/>

    Your Corporate Superpower is:<br/>
    <%= @hero_company_bs %><br/>
  </div>
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/home/team.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><%= link_to 'Click Here To Generate A New Superhero', root_path %></h3>
    </div>
    <div class="panel-body">
        TEAM PAGE
    </div>
    <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Superhero Name Generator</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'home/navbar' %>
        <div class="container">
            <%= yield %>
        </div>
        <br/><br/><br/><br/>
        <center>
            Written by: Rick Hays <br/>
        </center>
    </body>
</html>